create table department(dept_id int primary key,dept_name varchar(30));
 insert into department values(201,"HR");
 insert into department values(202,"BA");
 insert into department values(203,"Finance");
 insert into department values(204,"Dev");
 select * from department;
 create table employees(emp_id int primary key,emp_name varchar(30),salary int default 28000,department_id int,foreign key(department_id)references department(dept_id));
 select * from employees;
drop table employees;
select emp_name from employees where salary>34000;
select emp_name from employees where salary<40000;
select emp_name from employees where department_id>202;
select emp_name from employees where department_id=202;
select emp_name from employees where department_id!=202;
select emp_id from employees where salary>=35000;
select emp_name from employees where department_id=201 AND department_id=203;
select emp_name from employees where department_id=201 or department_id=203;
select emp_name from employees where department_id=201 and salary>34000;
select emp_name from employees where not salary=40000;
select * from employees where salary+70000>100000;
select max(Salary) from employees;
select min(Salary) from employees;
select sum(Salary) from employees;
select avg(Salary) from employees;
select count(Salary) from employees;
